import type { Metadata } from "next";
import Head from "next/head";
import "@/tailwind.css";

export const metadata: Metadata = {
  title: "Authentification",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </Head>
      <body>
        {children}
      </body>
    </html>
  );
}
