import type { Metadata } from "next";
import "@/tailwind.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
