import type { Metadata } from "next";
import "@/tailwind.css";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className="font-poppins">{children}</body>
    </html>
  );
}
